# Base settings
title: Alex Barbosa - Blog
author: Alex Barbosa
email: easbarba@outlook.com
description: >-
    Some thoughts on Emacs, Guix, and cool CLI software.
baseurl: "/blog"
url: "https://easbarba.github.io"
repository: easbarba/easbarba.github.io
twitter_username: easbarba
github_username: easbarba

# Build settings
markdown: kramdown
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
