# Base settings
title: Alex Barbosa - All the good Linux things
author: Alex Barbosa
email: easbarba@outlook.com
description: >-
    Articles on all the good Linux things.
#baseurl: "/blog"
url: "https://easbarba.github.io"
repository: easbarba/easbarba.github.io
github_username: easbarba

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
